name: Scrape Restaurant Status

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run scraper
        run: npm run scrape

      - name: Copy db.json to frontend dashboard
        run: cp backend/db.json frontend/dashboard/public/db.json

      - name: Commit scraped data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add backend/db.json frontend/dashboard/public/db.json
          git commit -m "Update scraped restaurant data"
          git push
        continue-on-error: true
